# Generated by Django 6.0.4 on 2026-04-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='departments',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='department',
            field=models.CharField(choices=[('dispatch', 'Dispatch'), ('update', 'Update'), ('safety', 'Safety'), ('fleet', 'Fleet'), ('accounting', 'Accounting'), ('recruiting', 'Recruiting'), ('career', 'Career Center')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(help_text='Question label shown to student', max_length=200),
        ),
    ]
