# Generated by Django 6.0.4 on 2026-04-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_examsession_departments_alter_question_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='exam_type',
            field=models.CharField(choices=[('mock', 'Mock Exam'), ('final', 'Final Exam')], default='mock', max_length=10),
        ),
    ]
