# Generated by Django 6.0.4 on 2026-04-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_examsession_exam_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsession',
            options={},
        ),
        migrations.AlterField(
            model_name='examsession',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='teacher',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
