# Generated by Django 6.0.4 on 2026-05-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_examsession_options_alter_examsession_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='department',
            field=models.CharField(choices=[('dispatch', 'Dispatch'), ('update', 'Update'), ('safety', 'Safety'), ('fleet', 'Fleet'), ('accounting', 'Accounting'), ('recruiting', 'Recruiting'), ('career', 'Career Center'), ('eng_mod1', 'Module 1: English Foundations'), ('eng_mod2', 'Module 2: Tenses & Timeline'), ('eng_mod3', 'Module 3: Advanced Communication')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('open', 'Open / Written'), ('scramble', 'Sentence Building')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='The full question text or scrambled words (separated by /)'),
        ),
    ]
