# Generated by Django 6.0.4 on 2026-05-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_question_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='block_reason',
            field=models.CharField(blank=True, help_text="Refresh yoki Tab o'zgarishi", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text="Talaba qoidani buzsa True bo'ladi"),
        ),
    ]
